version: '4'
services:
  redis:
    image: redis:6.2
    command: redis-server --databases 2
    ports:
      - "6379:6379"
    networks:
      - app-network

  pg-database:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
    depends_on:
      - redis
    networks:
      - app-network

  web:
    build: .
    command: rails server -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - pg-database
      - selenium
      - redis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWD: postgres
      POSTGRES_HOST: pg-database
      SELENIUM_DRIVER_URL: selenium
      REDIS_URL: redis://redis:6379/1
    networks:
      - app-network

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - '4444:4444'
    networks:
      - app-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
     - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - redis

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - pg-database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge